config/routes.rb
Rails.application.routes.draw do
  # root to: 'users#index'
  root 'books#index'
  devise_for :users

  #もしかしたらonly: [:new, :create, :index, :show]みたいなのいるかも〜！
  resources :books
  # post '/books/:id' => 'books#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end


def autheniticate_user
  if @current_user==nil
    flash[:notice]="ログインが必要です"
    redirect_to("/")
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    # {Book: title:"たいとる", body: "ボディ", user_id: nil.....}
    @book.user_id = current_user.id
    # {User: id:1, email: "e@e", name: "なまえ"........}
    # {Book: title:"たいとる", body: "ボディ", user_id: 1.....}
    if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book)
    else
        #indexアクションと同じ
        @books = Book.all
        render :index
    end
  end



  def index
    # @book.user_id = current_user.id
    @books = Book.all
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  # def update
  #   book = Book.find(params[:id])
  #   book.update(book_params)
  #   redirect_to book_params(book.id)
  # end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params) #（）内の指定の意味はprivate内のbook_paramsのtitle とbobyを引き出している
        flash[:notice] = "Book was successfully updated."
        redirect_to book_path(@book)
    else
        @books = Book.all
        render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>編集画面</h1>
<%= form_with model:@book, local: true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :body %>
  <%= f.submit 'Update Book' %>

  <%= link_to "show", book_path(@book) %>
  <%= link_to "back", books_path %>

<% end %>

app/views/books/index.html.erb
<h1>一覧ページです</h1>
<!--テーブルタグ使って見た目整える-->
<% @books.each do |book| %>
  <span><%= book.title %></span>
  <%= link_to "show", book_path(book.id) %>
  <%= link_to "edit", edit_book_path(book.id) %>
  <%= link_to "Destroy", book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<h1>本の新規作成</h1>
<%= form_with model:@book, url:'/books', local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>本の新規作成</h1>
<%= form_with model:@book, url:'/books', local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h1>本の新規作成</h1>
<%= form_with model:@book_new, url:'/books', local:true do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

<h1>詳細ページです</h1>
<p><%= @book.title %></p>
<p><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book) %>
<%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--以下navberコピペ改変まだ-->

    <div id="slidemenu">
    <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
      <% if user_signed_in? %>
        <li class="">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
        <li class="">
          <%= link_to '投稿フォーム', new_book_path %>
        </li>
        <li class="">
          <!-- ↓以下のコードは、5章で正しいroutingに書き直します。 -->
          <%= link_to 'マイページ', "#" %>
        </li>
      <% else %>
        <li class="">
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li class="">
          <%= link_to "ログイン", new_user_session_path %>
        </li>
      <% end %>
    </ul>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <i class="fas fa-book"></i>Bookers !!</h1>

    <p>In <i class="fas fa-book"></i><b>Bookers,</b></p>
    <p></p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>


   <!--ボタン配置-->

    <a href ='/users/sign_in'><button type="button" class="btn btn-info col-xs-10 col-xs-offset-1">Log in</button></a>
    <a href ='/users/sign_up'><button type="button" class="btn btn-success col-xs-10 col-xs-offset-1">Sign Up</button></a>
  </div>
</div>